<?php

namespace App\Helpers;

class ColorHelper
{
    /**
     * Comprehensive color name → hex mapping for textile industry.
     * Covers Sol's, NEOBLU, ATF, Roly, Kariban, Stanley/Stella color names.
     * For bicolor names (e.g. "Blanc / Marine"), returns the first color.
     */
    private const COLOR_MAP = [
        // ── Noirs ──
        'noir' => '#1A1A1A',
        'noir profond' => '#0D0D0D',
        'noir 2' => '#1A1A1A',
        'noir chiné' => '#333333',
        'noir recyclé' => '#1A1A1A',
        'black' => '#1A1A1A',
        'black heather' => '#333333',
        'black denim' => '#1C1C1C',
        'black rinse' => '#111111',
        'waved black' => '#1A1A1A',

        // ── Blancs / Crèmes ──
        'blanc' => '#FFFFFF',
        'blanc chiné' => '#F5F5F0',
        'white' => '#FFFFFF',
        'ecru' => '#F5F0E1',
        'écru' => '#F5F0E1',
        'crème' => '#FFFDD0',
        'naturel' => '#F5F0E1',
        'raw natural' => '#F0E8D8',
        'corde' => '#E8DCC8',

        // ── Gris ──
        'gris' => '#9E9E9E',
        'gris chiné' => '#A0A0A0',
        'gris chiné clair' => '#C8C8C8',
        'gris chiné foncé' => '#6E6E6E',
        'gris chiné recyclé' => '#A0A0A0',
        'gris clair' => '#C8C8C8',
        'gris foncé' => '#555555',
        'gris moyen' => '#8A8A8A',
        'gris perle' => '#D0D0D0',
        'gris pur' => '#B0B0B0',
        'gris souris' => '#7A7A7A',
        'gris léger' => '#D5D5D5',
        'gris flanelle' => '#6B6B6B',
        'gris carbone' => '#4A4A4A',
        'gris métal' => '#8E8E8E',
        'gris titanium' => '#6E6E6E',
        'gris urbain' => '#7D7D7D',
        'gris 2' => '#9E9E9E',
        'graphite' => '#4A4A4A',
        'anthracite' => '#3C3C3C',
        'anthracite chiné' => '#4A4A50',
        'anthracite foncé' => '#2E2E2E',
        'zinc' => '#A8A8A8',
        'silver' => '#C0C0C0',
        'grey heather' => '#A0A0A0',
        'grey melange' => '#A0A0A0',
        'ash heather' => '#B0B0B0',
        'light grey heather' => '#C8C8C8',
        'light grey melange' => '#C8C8C8',
        'dark grey heather' => '#5C5C5C',
        'deep grey heather' => '#505050',
        'marl grey' => '#9A9A9A',
        'marl dark grey' => '#5C5C5C',
        'marl silver' => '#BDBDBD',
        'marl storm grey' => '#6E6E6E',
        'oxford grey' => '#8A8E8C',
        'off grey' => '#B5B5B5',
        'cement grey heather' => '#9A9A9A',
        'granite grey heather' => '#7A7A7A',
        'steel grey heather' => '#707070',
        'tin grey heather' => '#8A8A8A',
        'titan grey heather' => '#6E6E6E',
        'shadow grey heather' => '#606060',
        'wise grey zebra' => '#7D7D7D',
        'slub grey heather' => '#9A9A9A',
        'snow grey melange' => '#D0D0D0',
        'alloy grey heather' => '#8A8A8A',
        'ashen grey heather' => '#B0B0B0',
        'graphite grey heather' => '#5C5C5C',
        'graphite blue heather' => '#5A6070',

        // ── Bleus ──
        'bleu' => '#2962FF',
        'bleu royal' => '#2962FF',
        'royal' => '#2962FF',
        'royal 2' => '#2962FF',
        'royal 3' => '#2962FF',
        'royal recyclé' => '#2962FF',
        'bleu roi' => '#2962FF',
        'bleu foncé' => '#1A237E',
        'bleu ciel' => '#87CEEB',
        'bleu clair' => '#90CAF9',
        'bleu léger' => '#BBDEFB',
        'bleu layette' => '#B3D4FC',
        'bleu moyen' => '#42A5F5',
        'bleu intense' => '#1565C0',
        'bleu atoll' => '#00ACC1',
        'bleu bugatti' => '#1976D2',
        'bleu canard' => '#006064',
        'bleu caraïbes' => '#00838F',
        'bleu piscine' => '#4DD0E1',
        'bleu glacier' => '#B2EBF2',
        'bleu arctique' => '#E0F7FA',
        'bleu abysse' => '#0D47A1',
        'bleu océan' => '#01579B',
        'bleu pétrole' => '#004D40',
        'bleu ardoise' => '#37474F',
        'bleu chiné' => '#5C6BC0',
        'bleu ciel chiné' => '#90CAF9',
        'bleu crémeux' => '#BBDEFB',
        'bleu foncé crémeux' => '#1A237E',
        'french marine' => '#1B2A4A',
        'french marine 2' => '#1B2A4A',
        'marine' => '#1B2A4A',
        'nuit' => '#1A1F3D',
        'nuit chiné' => '#2A2F4D',
        'ciel' => '#87CEEB',
        'ciel vif' => '#4FC3F7',
        'outremer' => '#1A237E',
        'denim' => '#5C7A99',
        'denim chiné' => '#7A99B5',
        'blue heather' => '#6A8CB0',
        'blue jean' => '#5C7A99',
        'blue rinse' => '#2C3E6B',
        'french navy heather' => '#2A3A5C',
        'ink navy' => '#192841',
        'off navy' => '#2A3A5C',
        'oxford blue' => '#1A2F5C',
        'oxford cobalt blue' => '#1A47B8',
        'oxford shadow navy' => '#1A2A4A',
        'night blue heather' => '#1A2A4A',
        'night navy heather' => '#1A2040',
        'night navy melange' => '#1A2040',
        'ocean blue heather' => '#3070A0',
        'turquoise blue heather' => '#00ACC1',
        'duck blue heather' => '#3E7A8C',
        'largo blue heather' => '#4A80A0',
        'abyss blue heather' => '#1A3A6A',
        'light blue heather' => '#90CAF9',
        'light royal blue jhoot' => '#4A80D0',
        'oxford light royal blue' => '#4A80D0',
        'oxford sky blue' => '#87CEEB',
        'cloudy blue heather' => '#90A4AE',

        // ── Rouges ──
        'rouge' => '#D32F2F',
        'rouge 2' => '#D32F2F',
        'rouge vif' => '#F44336',
        'rouge piment' => '#BF360C',
        'rouge coquelicot' => '#FF1744',
        'rouge tango' => '#E64A19',
        'rouge folk' => '#C62828',
        'rouge chiné' => '#D32F2F',
        'rouge recyclé' => '#D32F2F',
        'chili' => '#B71C1C',
        'oxblood' => '#800020',
        'oxblood chiné' => '#800020',

        // ── Roses ──
        'rose' => '#E91E63',
        'rose bonbon' => '#FF4081',
        'rose chiné' => '#F06292',
        'rose flash' => '#FF1493',
        'rose fluo' => '#FF69B4',
        'rose folk' => '#D81B60',
        'rose foncé' => '#C2185B',
        'rose layette' => '#F8BBD0',
        'rose moyen' => '#EC407A',
        'rose orchidée' => '#CE93D8',
        'rose poudré' => '#F0C8D0',
        'rose pâle' => '#FCE4EC',
        'rose ruban' => '#F06292',
        'rose crémeux' => '#FADADD',
        'fuchsia' => '#E91E90',
        'hibiscus' => '#E91E63',
        'candy pink heather' => '#F48FB1',
        'marl pink' => '#F48FB1',
        'oxford pink' => '#F48FB1',
        'oxford pale pink' => '#FADADD',
        'oxford lavender' => '#CE93D8',

        // ── Oranges ──
        'orange' => '#FF8F00',
        'orange 2' => '#FF8F00',
        'orange pop' => '#FF6D00',
        'orange brûlée' => '#E65100',
        'orange clair' => '#FFB74D',
        'orange foncé' => '#E65100',
        'orange moyen' => '#FB8C00',
        'orange fluo' => '#FF6D00',
        'neon orange' => '#FF6D00',
        'corail' => '#FF7043',
        'corail fluo' => '#FF5722',
        'coral heather' => '#FF8A80',
        'terracotta' => '#C75B39',
        'terra' => '#C75B39',
        'terre' => '#8D6E63',
        'terre d\'ombre' => '#5D4037',

        // ── Jaunes ──
        'jaune' => '#FDD835',
        'jaune clair' => '#FFF59D',
        'jaune fluo' => '#FFFF00',
        'jaune pâle' => '#FFFDE7',
        'citron' => '#CDDC39',
        'aurore' => '#FFD54F',
        'fluorescent yellow' => '#FFFF00',
        'straw' => '#E8D44D',
        'oxford yellow' => '#FDD835',

        // ── Verts ──
        'vert' => '#4CAF50',
        'vert pomme' => '#8BC34A',
        'vert bouteille' => '#1B5E20',
        'vert forêt' => '#2E7D32',
        'vert prairie' => '#43A047',
        'vert vif' => '#00C853',
        'vert printemps' => '#76FF03',
        'vert sapin' => '#1B5E20',
        'vert empire' => '#004D40',
        'vert glacé' => '#A5D6A7',
        'vert irlandais' => '#2E7D32',
        'vert golf' => '#388E3C',
        'vert pro' => '#2E7D32',
        'vert clair chiné' => '#A5D6A7',
        'vert crémeux' => '#C8E6C9',
        'vert fluo' => '#76FF03',
        'vert bourgeon' => '#7CB342',
        'vert absinthe' => '#9CCC65',
        'vert foncé 2' => '#1B5E20',
        'vert jaune' => '#CDDC39',
        'lime' => '#CDDC39',
        'lime fluo' => '#C6FF00',
        'tilleul' => '#AED581',
        'kaki' => '#6D6B3D',
        'kaki chiné' => '#6D6B3D',
        'kaki foncé' => '#4A4B2E',
        'kaki intense' => '#5D5C2E',
        'army' => '#4B5320',
        'seagrass' => '#8FBC8F',
        'emeraude' => '#00897B',
        'turquoise' => '#00BCD4',
        'aqua' => '#00BCD4',
        'mint' => '#A7FFEB',
        'fluorescent green' => '#76FF03',
        'marl green' => '#66BB6A',
        'green marble heather' => '#5A8A5A',
        'oxford green' => '#2E7D32',
        'oxford zinc' => '#A8A8A0',
        'oxford mastic' => '#C8B89A',
        'dark khaki heather' => '#5A5A3A',
        'light khaki heather' => '#8A8A6A',
        'dusty green' => '#78A87A',

        // ── Violets ──
        'violet' => '#7B1FA2',
        'violet foncé' => '#4A148C',
        'violet clair' => '#CE93D8',
        'violet astral' => '#7E57C2',
        'lilas' => '#CE93D8',
        'wine heather' => '#6A1B3A',

        // ── Marrons / Beiges ──
        'bordeaux' => '#800020',
        'bordeaux moyen' => '#9A1A3A',
        'chocolat' => '#5D4037',
        'chocolat foncé' => '#3E2723',
        'marron' => '#795548',
        'brun clair' => '#A1887F',
        'châtaigne' => '#8D6E63',
        'taupe' => '#8B8680',
        'beige' => '#D7C9A8',
        'beige chiné' => '#D7C9A8',
        'beige foncé' => '#B5A080',
        'beige heather' => '#D7C9A8',
        'camel heather' => '#C19A6B',
        'sable' => '#D2B48C',
        'dune' => '#D2C2A0',
        'raphia' => '#C4AA78',
        'mastic' => '#C8B89A',
        'vieux rose' => '#C08080',
        'dusty beige' => '#C8B8A0',
        'sand heather' => '#D2B48C',
        'dull brown' => '#8B7355',
        'tawny port heather' => '#6A1B3A',
        'dark khaki leopard' => '#5A5A3A',
        'herringbone chocolate' => '#5D4037',
        'herringbone grey' => '#8A8A8A',
        'herringbone light grey' => '#B0B0B0',
        'herringbone sand' => '#D2B48C',
        'oxford silver' => '#C0C0C0',

        // ── Camouflages ──
        'camouflage' => '#5A5A3A',
        'camo' => '#5A5A3A',
        'camo bleu' => '#3A5A6A',
        'camo gris' => '#6A6A6A',
        'brown camouflage' => '#6A5A3A',
        'grey camouflage' => '#6A6A6A',
        'jungle camo' => '#4A5A2A',
        'olive camouflage' => '#5A6A3A',
        'khaki camouflage' => '#5A5A3A',

        // ── Denim ──
        'brut denim' => '#2C3E6B',
        'raw denim' => '#2C3E6B',
        'dark blue denim' => '#1A2A5C',
        'recycled denim' => '#5C7A99',
        'stone wash' => '#8AA0B8',
        'jean chiné clair' => '#90A8C0',

        // ── Spéciaux Heather/Checked ──
        'marine checked' => '#1B2A4A',
        'bordeaux checked' => '#800020',
        'black leopard' => '#1A1A1A',
        'navy leopard' => '#1B2A4A',

        // ── Marine prowear ──
        'marine prowear' => '#1B2A4A',
        'marine recyclé' => '#1B2A4A',

        // ── Sporty / Bicolores courants ──
        'sporty royal blue heather' => '#2962FF',
        'french navy heather / grey heather' => '#2A3A5C',
        'grey heather / black' => '#A0A0A0',
        'dark grey heather / black' => '#5C5C5C',
        'pêche' => '#FFDAB9',
        'lin' => '#D4C5A9',
        'red melange' => '#D32F2F',
        'baby blue' => '#89CFF0',
        'abricot' => '#E9967A',
        'vegetal paper' => '#C8B89A',
        'jacquard blue' => '#3A5A8C',
        'jacquard dark grey' => '#4A4A4A',
        'melange jhoot' => '#9A9A9A',
        'dark shadow heather' => '#4A4A4A',
        'striped ecume' => '#E8E0D0',

        // ── Roly — couleurs espagnoles & spécifiques ──
        'almendra' => '#EFDECD',
        'amarillo curry' => '#CDA317',
        'amarillo maíz' => '#FBEC5D',
        'amarillo sweet' => '#FFE066',
        'amarillo sweet lavado' => '#FFE066',
        'ananas' => '#FFD700',
        'arándano' => '#4F86C6',
        'arbre' => '#2D5F2D',
        'argent' => '#C0C0C0',
        'azul calma' => '#5B9BD5',
        'azul cobalto' => '#0047AB',
        'azul lago' => '#4682B4',
        'azul sweet' => '#87CEEB',
        'azul tormenta' => '#4F6D7A',
        'bambou' => '#D4C89A',
        'bois' => '#8B6914',
        'bourgogne' => '#800020',
        'burgundy' => '#800020',
        'café' => '#6F4E37',
        'camel' => '#C19A6B',
        'cereza' => '#DE3163',
        'citrus' => '#9FA91F',
        'cobre' => '#B87333',
        'ébène' => '#3C3024',
        'ébène chiné' => '#4A3C30',
        'fraise' => '#FC5A8D',
        'framboise' => '#C72C48',
        'grenat' => '#6C0000',
        'grenat chiné' => '#7A2020',
        'iris purple' => '#5D3FD3',
        'jade' => '#00A86B',
        'jeans' => '#4A6FA5',
        'kiwi' => '#8EE53F',
        'lavande' => '#B57EDC',
        'lila' => '#C8A2C8',
        'menta oscuro' => '#3EB489',
        'moka' => '#967969',
        'moutarde' => '#C7A317',
        'moutarde chiné' => '#C7A317',
        'multi couleur' => '#FF6B6B',
        'naranja fuego' => '#FF4500',
        'noyer' => '#5C4033',
        'nude' => '#F2D2BD',
        'ocre' => '#CC7722',
        'oliva' => '#808000',
        'opale' => '#A8C3BC',
        'or' => '#FFD700',
        'orchidée' => '#DA70D6',
        'pastèque' => '#FC6C85',
        'pistache' => '#93C572',
        'plomb' => '#808080',
        'plomb foncé' => '#5A5A5A',
        'pomme' => '#66B032',
        'pourpre' => '#800080',
        'raisin' => '#6B3FA0',
        'rojo baya' => '#A52A2A',
        'rojo ciruela' => '#8E4585',
        'rojo oscuro' => '#8B0000',
        'rojo pálido' => '#DB7093',
        'rosa seda' => '#FFB7C5',
        'rosacé' => '#FF69B4',
        'rosacé chiné' => '#FF85C1',
        'teja' => '#C04000',
        'tomate' => '#FF6347',
        'transparent' => '#EEEEEE',
        'turquesa fluor' => '#00FFD5',
        'verde humo' => '#708B75',
        'verde laurel' => '#2E8B57',
        'verde oscuro' => '#006400',
        'verde pato lavado' => '#568203',
        'verde salvia' => '#9CAF88',
        'verde vigoré' => '#6B8E6B',
        'papaya claro lavado' => '#FFDAB9',
        'fusión marino' => '#003366',
        'fusión morado' => '#7B287D',
        'fusón rosa' => '#FF66B2',
        'rojo carbón vigoré' => '#8B2500',

        // ── English / Imbretex brands (AWDis, B&C, Fruit of the Loom, Result, Bag Base, Beechfield, Westford Mill) ──
        'acid grey' => '#B4B4B4',
        'acid lime' => '#BFFF00',
        'airforce blue' => '#5D8AA8',
        'almond' => '#EFDECD',
        'almond marl' => '#E8D8C4',
        'alpine blues' => '#4A7FB5',
        'alpine peaks' => '#D8E4E8',
        'amalfi blue' => '#3B7DD8',
        'amalfi coral' => '#FF6F61',
        'amalfi green' => '#5FA778',
        'amalfi grey' => '#9A9A9A',
        'amalfi teal' => '#367588',
        'amalfi yellow' => '#F5D547',
        'amber' => '#FFBF00',
        'antique grey' => '#A8A8A0',
        'antique mustard' => '#C8A830',
        'apple green' => '#8DB600',
        'arctic camo' => '#C8D0D8',
        'arctic down' => '#E8EEF0',
        'arctic white' => '#F8F8FF',
        'ash' => '#B2BEB5',
        'athletic heather' => '#A0A0A0',
        'atlantic blue' => '#1A4B8C',
        'atoll' => '#00ACC1',
        'autumn moss' => '#6B7C3F',
        'azure' => '#007FFF',
        'azure blue' => '#2C75FF',
        'baby pink' => '#F4C2C2',
        'biscuit' => '#D4A76A',
        'biscuit stripe' => '#D4A76A',
        'black cherry' => '#3B0910',
        'black jacks' => '#1A1A1A',
        'black marl' => '#2A2A2A',
        'black onyx' => '#0F0F0F',
        'black reflective' => '#1A1A1A',
        'black smoke' => '#2A2A30',
        'blossom' => '#FFB7C5',
        'blue cloud' => '#B0C4DE',
        'blue grey' => '#6699CC',
        'blue linen' => '#8CA8C4',
        'blue topaz' => '#0F97A8',
        'blueberry cheesecake' => '#4F86C6',
        'blueberry swirl' => '#4F6DA8',
        'blush' => '#DE5D83',
        'blush blue' => '#9AB8D8',
        'blush mint' => '#AAD8C0',
        'blush pink' => '#FE828C',
        'bottle' => '#1B5E20',
        'bottle green' => '#1B5E20',
        'brick red' => '#CB4154',
        'bright blue' => '#0066FF',
        'bright green' => '#66FF00',
        'bright lavender' => '#BF94E4',
        'bright olive' => '#6B8E23',
        'bright pink' => '#FF007F',
        'bright red' => '#EE4035',
        'bright royal' => '#2962FF',
        'brown' => '#8B4513',
        'brown check' => '#8B4513',
        'burnt orange' => '#CC5500',
        'cactus green' => '#5C7A3A',
        'camo green' => '#4A5A2A',
        'candy pink' => '#E4717A',
        'candyfloss pink' => '#FFB7D5',
        'cappuccino' => '#A38060',
        'caramel' => '#C68E17',
        'caramel latte' => '#C8A882',
        'caramel toffee' => '#B5792A',
        'celtic green' => '#2D6A2D',
        'charcoal' => '#36454F',
        'charcoal grey' => '#3D3D3D',
        'charcoal herringbone' => '#3D3D3D',
        'charcoal marl' => '#444444',
        'charcoal melange' => '#444444',
        'cherry sherbet' => '#E05070',
        'chilli blues' => '#3A4A8A',
        'chilli red' => '#C21807',
        'chocolate brown' => '#3E2723',
        'chocolate fudge brownie' => '#3B1F0A',
        'classic olive' => '#6B8E23',
        'classic pink' => '#F8C8DC',
        'classic red' => '#D32F2F',
        'clay' => '#B66A50',
        'clear' => '#EEEEEE',
        'cloud grey' => '#C8CDD0',
        'cloudy haze' => '#C8D0D8',
        'cobalt blue' => '#0047AB',
        'cobalt navy' => '#003478',
        'college green' => '#1E5631',
        'combat camo' => '#4A5A2A',
        'combat green' => '#4A5A2A',
        'cool grey' => '#9AA0A8',
        'coral' => '#FF7F50',
        'cornflower blue' => '#6495ED',
        'crackling campfire' => '#B84A1A',
        'cranberry' => '#9F1D35',
        'dark emerald' => '#004D40',
        'dark forest' => '#0B3B0B',
        'dark graphite' => '#383838',
        'dark grey' => '#555555',
        'dark heather grey' => '#5A5A5A',
        'dark marine' => '#0A1A30',
        'dark olive' => '#3C3C1A',
        'dark plum' => '#4A0040',
        'dark royal' => '#003DA5',
        'deep black' => '#0A0A0A',
        'deep navy' => '#0A0A3C',
        'deep red' => '#8B0000',
        'deep sea blue' => '#1A3A5C',
        'denim blue' => '#4A6FA5',
        'desert peaks' => '#D2B48C',
        'desert sand' => '#EDC9AF',
        'digital lavender' => '#B8A9D9',
        'dijon blue' => '#3A5A8C',
        'dove grey' => '#B0AFA8',
        'duck egg blue' => '#B0D0D3',
        'dusky pink' => '#CC8899',
        'dusty blue' => '#6699AA',
        'dusty lilac' => '#B8A9C9',
        'dusty pink' => '#DCAE96',
        'dusty purple' => '#8A6A8A',
        'dusty rose' => '#C4767A',
        'dusty turquoise' => '#5A9A9A',
        'earthy green' => '#5A6B3A',
        'electric green' => '#00FF00',
        'electric grey' => '#9A9AA0',
        'electric orange' => '#FF5300',
        'electric pink' => '#FF1493',
        'electric yellow' => '#FFFF33',
        'emerald' => '#50C878',
        'emerald green' => '#046307',
        'espresso haze' => '#4A2C2A',
        'fennel' => '#90A955',
        'festival fuchsia' => '#FF00FF',
        'field camo' => '#5A5A3A',
        'fire red' => '#CE2029',
        'flame' => '#E25822',
        'fluo orange' => '#FF6600',
        'fluo pink' => '#FF1493',
        'fluo yellow' => '#CCFF00',
        'fluorescent orange' => '#FF6600',
        'fluorescent pink' => '#FF1493',
        'forager fusion' => '#5A7A4A',
        'forest green' => '#228B22',
        'forest night' => '#0B2B0B',
        'french navy' => '#1B2A4A',
        'fresh green' => '#4CAF50',
        'fresh pink' => '#FF69B4',
        'frost grey' => '#CBD0D4',
        'ginger biscuit' => '#C49A6C',
        'glacier peaks' => '#D0E0E8',
        'gold' => '#FFD700',
        'granite' => '#676767',
        'graphite grey' => '#4A4A4A',
        'graphite heather' => '#505050',
        'green camo' => '#4A5A2A',
        'green check' => '#2E7D32',
        'green moss' => '#5A6B3A',
        'grey' => '#808080',
        'grey camo' => '#6A6A6A',
        'grey check' => '#808080',
        'grey linen' => '#B0B0AA',
        'grey marl' => '#9A9A9A',
        'grey pink marble' => '#C0A0A0',
        'grey stripe' => '#9A9A9A',
        'gunmetal grey' => '#536878',
        'hawaiian blue' => '#00BFFF',
        'hazel' => '#8E7618',
        'hazelnut' => '#A0724A',
        'heather blue' => '#6A8CB0',
        'heather burgundy' => '#7A2040',
        'heather graphite' => '#555558',
        'heather green' => '#5A8A5A',
        'heather grey' => '#9A9AA0',
        'heather grey fog' => '#B0B0B8',
        'heather navy' => '#2A3A5C',
        'heather oatmeal' => '#D0C8B8',
        'heather purple' => '#7A5A8A',
        'heather red' => '#C04040',
        'heather royal' => '#3A5ACA',
        'heather tarmac' => '#5A5A5A',
        'hot chocolate' => '#3B1E0A',
        'hot pink' => '#FF69B4',
        'hyper pink' => '#FF1493',
        'ice blue' => '#D6ECEF',
        'ice grey' => '#D8DCE0',
        'indigo' => '#4B0082',
        'indigo blue' => '#3F51B5',
        'indigo camo' => '#3A3A6A',
        'ink blue' => '#1A2A5C',
        'iron grey' => '#48494B',
        'ivy green' => '#2E5A2E',
        'jet black' => '#0A0A0A',
        'kelly green' => '#4CBB17',
        'khaki' => '#C3B091',
        'lagoon blue' => '#008B8B',
        'lake blue' => '#4A80B0',
        'lavender' => '#B57EDC',
        'lavender fizz' => '#C8A8E8',
        'lemon' => '#FFF44F',
        'leopard print' => '#C8A060',
        'lic green' => '#76FF03',
        'light denim' => '#8CA8C4',
        'light graphite' => '#6A6A6A',
        'light grey' => '#C0C0C0',
        'light grey fleck' => '#C8C8C8',
        'light grey marl' => '#CCCCCC',
        'light navy' => '#2A3A5C',
        'light orange' => '#FFB347',
        'light pink' => '#FFB6C1',
        'lilac' => '#C8A2C8',
        'lime green' => '#32CD32',
        'lipstick pink' => '#E75480',
        'lotus blue' => '#4A6FA5',
        'lotus pink' => '#E8A0B8',
        'magenta' => '#FF0090',
        'magenta magic' => '#FF0090',
        'magenta pink' => '#FF0080',
        'mango sorbet' => '#FF8C00',
        'marine green' => '#1A5A4A',
        'marine splash' => '#1A6A8A',
        'mellow yellow' => '#F8E473',
        'melon orange' => '#F5A040',
        'meta fuchsia' => '#FF00FF',
        'meta gold' => '#FFD700',
        'meta lilac' => '#D0A0E0',
        'meta orange' => '#FF6600',
        'meta turquoise' => '#00CED1',
        'mid blue' => '#4A80D0',
        'midnight camo' => '#1A2A3A',
        'midnight haze' => '#1A1A3A',
        'military green' => '#4B5320',
        'milkshake mix' => '#F0D0D0',
        'millennial lilac' => '#C8A8D8',
        'mineral blue' => '#4A6A8A',
        'mineral green' => '#3A6A4A',
        'mint green' => '#98FB98',
        'mint choc chip' => '#A0D8B0',
        'mocha brown' => '#6F4E37',
        'moondust grey' => '#B0B0B8',
        'moonstone' => '#3AA8C1',
        'morning frost' => '#E0E8E4',
        'moss green' => '#4A5A2A',
        'mountain blue' => '#3A5A8C',
        'mushroom' => '#BAA38C',
        'mustard' => '#E1AD01',
        'myrobalan stone' => '#C8B89A',
        'natural' => '#F5F0E1',
        'natural stone' => '#D2C8B0',
        'navy' => '#1B2A4A',
        'navy dusk' => '#1A2040',
        'navy fleck' => '#1B2A4A',
        'navy herringbone' => '#1B2A4A',
        'navy pure' => '#0A1A3C',
        'navy smoke' => '#2A3A4A',
        'navy stripe' => '#1B2A4A',
        'neon green' => '#39FF14',
        'new french navy' => '#1B2A4A',
        'nordic blue' => '#4A6A8A',
        'nude pink' => '#F2D2BD',
        'oatmeal' => '#D8C8A8',
        'oatmeal fleck' => '#D8C8A8',
        'ocean blue' => '#0077BE',
        'ocean teal' => '#1A6A7A',
        'off white' => '#FAF0E6',
        'olive' => '#808000',
        'olive camo' => '#5A5A3A',
        'olive green' => '#6B8E23',
        'orange crush' => '#FF6600',
        'orange flame' => '#FF5722',
        'orange rust' => '#C04000',
        'orchid green' => '#5A8A6A',
        'orchid pink' => '#DA70D6',
        'oxford navy' => '#0A1A3A',
        'oyster' => '#D7CFC2',
        'pacific grey' => '#8A9AA0',
        'paramedic green' => '#00703C',
        'pastel blue' => '#AEC6CF',
        'pastel lemon' => '#FFFACD',
        'pastel mint' => '#A8E8C8',
        'pastel pink' => '#FFD1DC',
        'pastel sunset dip' => '#FFB6A0',
        'peach' => '#FFCBA4',
        'peach perfect' => '#FFD0B0',
        'peach sorbet' => '#FFDAB9',
        'pebble' => '#B0A898',
        'peppermint' => '#A8D8C0',
        'petrol' => '#005A5A',
        'pina colada' => '#FFF0C0',
        'pine green' => '#01786F',
        'pink' => '#FFC0CB',
        'pink camo' => '#E0A0B0',
        'pink check' => '#FFC0CB',
        'pistachio' => '#93C572',
        'pistachio green' => '#93C572',
        'pixel lime' => '#BFFF00',
        'platinium grey' => '#B0B0B0',
        'plum' => '#8E4585',
        'pomegranate rose' => '#C04060',
        'pop green' => '#00E050',
        'pop tomato' => '#FF4040',
        'pop turquoise' => '#00E0D0',
        'pop yellow' => '#FFE000',
        'powder blue' => '#B0D4E8',
        'powder pink' => '#FFD0D8',
        'powder rose' => '#E8A0A8',
        'pumpkin' => '#FF7518',
        'pumpkin pie' => '#E67A20',
        'pure green' => '#00A550',
        'pure grey' => '#B0B0B0',
        'pure orange' => '#FF6600',
        'pure red' => '#EE0000',
        'purple' => '#800080',
        'putty' => '#C8B89A',
        'radiant purple' => '#8A2BE2',
        'rainbow' => '#FF6B6B',
        'rainforest green' => '#1A5A2A',
        'raspberry' => '#E30B5C',
        'raspberry pink' => '#E4007C',
        'raspberry ripple' => '#D0406A',
        'red' => '#D32F2F',
        'red hot chili' => '#C21807',
        'red hot chilli' => '#C21807',
        'red rust' => '#A52019',
        'red stripe' => '#D32F2F',
        'redwood' => '#8A3324',
        'reflex blue' => '#001489',
        'retro blues' => '#4A6A8A',
        'retro heather green' => '#5A8A5A',
        'retro heather royal' => '#3A5ACA',
        'ribbon pink' => '#F06292',
        'roasted coffee' => '#4A2C1A',
        'rocky peaks' => '#9A9A9A',
        'rose' => '#FF007F',
        'rose gold' => '#B76E79',
        'rose pink' => '#FF66CC',
        'rose quartz' => '#AA98A9',
        'royal blue' => '#2962FF',
        'ruby red' => '#9B111E',
        'rust' => '#B7410E',
        'saffron' => '#F4C430',
        'sage' => '#9CAF88',
        'sage green' => '#9CAF88',
        'sand' => '#D2B48C',
        'sand black tie dye' => '#C4AA78',
        'sapphire' => '#0F52BA',
        'sapphire blue' => '#0F52BA',
        'scarlet red' => '#FF2400',
        'sea salt' => '#D8E4E0',
        'seafoam' => '#93E9BE',
        'shark grey' => '#808B96',
        'sherbet lemon' => '#F5E050',
        'silver grey' => '#BDBDBD',
        'silver reflective' => '#C0C0C0',
        'sky' => '#87CEEB',
        'sky blue' => '#87CEEB',
        'slate blue' => '#6A5ACD',
        'smoke grey' => '#7A7A7A',
        'soft blue' => '#A8C8E8',
        'soft grey' => '#C0C0C0',
        'soft lavender' => '#C8A8D8',
        'soft mint' => '#A8E8D0',
        'soft pink' => '#FFD0D8',
        'soft red' => '#E05050',
        'soft rose' => '#E8A0B0',
        'soft white' => '#F8F8F0',
        'solar yellow' => '#FFD700',
        'solid charcoal' => '#36454F',
        'spacer olive' => '#6B6B3D',
        'sport grey' => '#9A9A9A',
        'sports grey' => '#9A9A9A',
        'spring green' => '#00FF7F',
        'steel blue' => '#4682B4',
        'steel grey' => '#6C6C6C',
        'stone' => '#C8B89A',
        'storm grey' => '#6E6E6E',
        'strawberry haze' => '#E8606A',
        'sun yellow' => '#FFD700',
        'sunflower' => '#FFDA03',
        'sunset' => '#FAD6A5',
        'surf blue' => '#4A90B8',
        'surf ocean' => '#2A7A8A',
        'surf pink' => '#F8A0B0',
        'surf purple' => '#7A5A9A',
        'tahiti coral' => '#FF6F61',
        'tan' => '#D2B48C',
        'teal' => '#008080',
        'tie-dye swirl' => '#FF6B6B',
        'tropical blue' => '#00B8D4',
        'true pink' => '#FF69B4',
        'true violet' => '#8B00FF',
        'truffle' => '#6A4A3A',
        'turquoise blue' => '#00CED1',
        'turquoise surf' => '#00B4A8',
        'urban camo' => '#5A5A5A',
        'urban khaki' => '#6D6B3D',
        'vanilla' => '#F3E5AB',
        'vanilla milkshake' => '#FFF5E0',
        'vintage aqua' => '#7AC5CD',
        'vintage black' => '#2A2A2A',
        'vintage bottle green' => '#2E5A2E',
        'vintage brown' => '#6B4226',
        'vintage cornflower' => '#6495ED',
        'vintage denim' => '#5C7A99',
        'vintage dusky pink' => '#CC8899',
        'vintage heather navy' => '#2A3A5C',
        'vintage heather red' => '#C04040',
        'vintage jungle camo' => '#4A5A2A',
        'vintage leopard print' => '#C8A060',
        'vintage light blue' => '#90B8D8',
        'vintage light denim' => '#8CA8C4',
        'vintage military green' => '#4B5320',
        'vintage moss' => '#5A6B3A',
        'vintage olive' => '#6B6B3D',
        'vintage orange' => '#E86830',
        'vintage orange rust' => '#C04000',
        'vintage oxblood' => '#800020',
        'vintage peach' => '#FFDAB9',
        'vintage red' => '#C0392B',
        'vintage sage green' => '#9CAF88',
        'vintage sand' => '#D2B48C',
        'vintage stone' => '#C8B89A',
        'vintage true pink' => '#FF69B4',
        'vivid blue' => '#0080FF',
        'vivid green' => '#00CC00',
        'walnut' => '#6B4226',
        'warm sand' => '#D8C0A0',
        'watermelon breeze' => '#FD4659',
        'winter berries' => '#6A1A3A',
        'workguard grey' => '#808080',
        'yellow' => '#FFD700',
        'cookies&cream' => '#E8D8C4',
    ];

    /**
     * Resolve hex code from color name (primary) or Pantone code (fallback).
     */
    public static function resolve(string $colorName, mixed $pantoneCode = null): ?string
    {
        // Try exact match on lowercased, trimmed name
        $key = mb_strtolower(trim($colorName));
        if (isset(self::COLOR_MAP[$key])) {
            return self::COLOR_MAP[$key];
        }

        // For bicolor names like "Blanc / Marine", try the first color
        if (str_contains($key, '/')) {
            $firstPart = trim(explode('/', $key)[0]);
            if (isset(self::COLOR_MAP[$firstPart])) {
                return self::COLOR_MAP[$firstPart];
            }
        }

        // Try partial matching: find the longest matching key contained in the name
        $bestMatch = null;
        $bestLen = 0;
        foreach (self::COLOR_MAP as $mapKey => $hex) {
            if (str_contains($key, $mapKey) && mb_strlen($mapKey) > $bestLen) {
                $bestMatch = $hex;
                $bestLen = mb_strlen($mapKey);
            }
        }
        if ($bestMatch) {
            return $bestMatch;
        }

        // Fallback: Pantone TCX → hex
        if ($pantoneCode) {
            return self::pantoneToHex($pantoneCode);
        }

        return null;
    }

    /**
     * Pantone TCX → hex approximation (fallback).
     */
    public static function pantoneToHex(mixed $pantone): ?string
    {
        if (is_array($pantone)) {
            $pantone = $pantone[0] ?? '';
        }
        $pantone = (string) $pantone;
        if (empty($pantone)) {
            return null;
        }

        $map = [
            '19-4007 TCX' => '#2B2B2B',
            '19-4010 TCX' => '#1C1C3A',
            '19-1664 TCX' => '#C62828',
            '11-0601 TCX' => '#F5F5F0',
            '19-3921 TCX' => '#2C3E8C',
            '14-4112 TCX' => '#87CEEB',
            '17-4041 TCX' => '#4682B4',
            '19-3952 TCX' => '#3949AB',
            '18-1662 TCX' => '#E53935',
            '18-0130 TCX' => '#2E7D32',
            '16-1054 TCX' => '#FFB300',
            '14-0837 TCX' => '#FDD835',
            '19-1101 TCX' => '#3E2723',
            '15-1040 TCX' => '#FF8F00',
            '17-3826 TCX' => '#7E57C2',
            '15-3817 TCX' => '#CE93D8',
            '14-1318 TCX' => '#FFAB91',
            '12-0720 TCX' => '#FFF9C4',
            '15-6437 TCX' => '#66BB6A',
            '18-4051 TCX' => '#1976D2',
            '19-0509 TCX' => '#455A64',
            '17-5104 TCX' => '#9E9E9E',
            '14-4002 TCX' => '#CFD8DC',
            '19-1725 TCX' => '#880E4F',
            '16-1546 TCX' => '#FF7043',
        ];

        return $map[$pantone] ?? null;
    }

    /**
     * Get all color names in the map (for debugging).
     */
    public static function allMappedNames(): array
    {
        return array_keys(self::COLOR_MAP);
    }
}
